# Generated by Django 2.0.3 on 2018-10-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Referral_Mentor',
        ),
        migrations.DeleteModel(
            name='Referral_SubMentor',
        ),
        migrations.DeleteModel(
            name='Referral_Trainee',
        ),
    ]
