# Generated by Django 2.0.3 on 2018-10-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181018_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='submentor',
            name='referral_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
