# Generated by Django 2.0.3 on 2018-10-19 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181018_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='refral_count',
            new_name='referral_count',
        ),
        migrations.RenameField(
            model_name='trainee',
            old_name='refral_count',
            new_name='referral_count',
        ),
    ]
