# Generated by Django 2.0.3 on 2018-10-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181019_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='referral_count',
            new_name='refral_count',
        ),
        migrations.RenameField(
            model_name='trainee',
            old_name='referral_count',
            new_name='refral_count',
        ),
        migrations.RemoveField(
            model_name='submentor',
            name='refral_count',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Trainee'), (2, 'Industry Expert'), (3, 'Moderator'), (4, 'Associate Project Mentor')], null=True),
        ),
    ]
