# Generated by Django 2.0.3 on 2018-10-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submentor',
            old_name='subcourses',
            new_name='courses',
        ),
        migrations.RenameField(
            model_name='submentor',
            old_name='subprojects',
            new_name='projects',
        ),
        migrations.RemoveField(
            model_name='submentor',
            name='subskills',
        ),
        migrations.AddField(
            model_name='submentor',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='subskills', to='core.Skill'),
        ),
        migrations.DeleteModel(
            name='subSkill',
        ),
    ]
