# Generated by Django 2.0.3 on 2018-10-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181020_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submentor',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
