# Generated by Django 2.0.3 on 2018-10-20 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181020_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='code',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='referral_count',
        ),
        migrations.RemoveField(
            model_name='submentor',
            name='code',
        ),
        migrations.RemoveField(
            model_name='submentor',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='submentor',
            name='referral_count',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='code',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='referral_count',
        ),
    ]
