# Generated by Django 2.0.3 on 2018-10-21 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181021_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='refferal_order',
            field=models.IntegerField(blank=True, default=100, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
