# Generated by Django 2.0.3 on 2018-10-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_lesson_refferal_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='accepted_list',
            field=models.ManyToManyField(blank=True, related_name='accepted_list', to='core.SubMentor'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='pending_list',
            field=models.ManyToManyField(blank=True, related_name='pending_list', to='core.SubMentor'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='rejected_list',
            field=models.ManyToManyField(blank=True, related_name='rejected_list', to='core.SubMentor'),
        ),
    ]
