# Generated by Django 2.0.3 on 2018-10-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20181022_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='accepted_list',
        ),
        migrations.AddField(
            model_name='mentor',
            name='accepted_list',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='pending_list',
        ),
        migrations.AddField(
            model_name='mentor',
            name='pending_list',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='rejected_list',
        ),
        migrations.AddField(
            model_name='mentor',
            name='rejected_list',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
