# Generated by Django 2.0.3 on 2018-10-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20181022_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accepted_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pending_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='accepted_list',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='pending_list',
        ),
        migrations.AddField(
            model_name='mentor',
            name='accepted_list',
            field=models.ManyToManyField(blank=True, related_name='accepted_list', to='core.Accepted_list'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='pending_list',
            field=models.ManyToManyField(blank=True, related_name='pending_list', to='core.Accepted_list'),
        ),
    ]
