# Generated by Django 2.0.3 on 2018-10-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20181022_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='accepted_list',
            name='accepted_name',
        ),
        migrations.AlterField(
            model_name='mentor',
            name='pending_list',
            field=models.ManyToManyField(blank=True, related_name='pending_list', to='core.Pending_list'),
        ),
        migrations.RemoveField(
            model_name='pending_list',
            name='pending_name',
        ),
        migrations.AddField(
            model_name='accepted_list',
            name='accepted_name',
            field=models.ManyToManyField(blank=True, related_name='accepted_name', to='core.Names'),
        ),
        migrations.AddField(
            model_name='pending_list',
            name='pending_name',
            field=models.ManyToManyField(blank=True, related_name='pending_name', to='core.Names'),
        ),
    ]
