# Generated by Django 2.0.3 on 2018-10-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20181024_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accepted_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pending_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_name', models.ManyToManyField(blank=True, related_name='pending_name', to='core.Names')),
                ('spending_name', models.ManyToManyField(blank=True, related_name='spending_name', to='core.Names')),
            ],
        ),
        migrations.CreateModel(
            name='Rejected_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejected_name', models.ManyToManyField(blank=True, related_name='rejected_name', to='core.Names')),
                ('srejected_name', models.ManyToManyField(blank=True, related_name='srejected_name', to='core.Names')),
            ],
        ),
        migrations.AlterField(
            model_name='mentor',
            name='accepted_list',
            field=models.ManyToManyField(blank=True, related_name='accepted_list', to='core.Accepted_list'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='pending_list',
            field=models.ManyToManyField(blank=True, related_name='pending_list', to='core.Pending_list'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='rejected_list',
            field=models.ManyToManyField(blank=True, related_name='rejected_list', to='core.Rejected_list'),
        ),
        migrations.AddField(
            model_name='accepted_list',
            name='accepted_name',
            field=models.ManyToManyField(blank=True, related_name='accepted_name', to='core.Names'),
        ),
        migrations.AddField(
            model_name='accepted_list',
            name='saccepted_name',
            field=models.ManyToManyField(blank=True, related_name='saccepted_name', to='core.Names'),
        ),
        migrations.AddField(
            model_name='submentor',
            name='accepted_list',
            field=models.ManyToManyField(blank=True, related_name='saccepted_list', to='core.Accepted_list'),
        ),
        migrations.AddField(
            model_name='submentor',
            name='pending_list',
            field=models.ManyToManyField(blank=True, related_name='spending_list', to='core.Pending_list'),
        ),
        migrations.AddField(
            model_name='submentor',
            name='rejected_list',
            field=models.ManyToManyField(blank=True, related_name='srejected_list', to='core.Rejected_list'),
        ),
    ]
