# Generated by Django 2.0.3 on 2018-10-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20181024_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submentor',
            old_name='accepted_list',
            new_name='saccepted_list',
        ),
        migrations.RenameField(
            model_name='submentor',
            old_name='pending_list',
            new_name='spending_list',
        ),
        migrations.RenameField(
            model_name='submentor',
            old_name='rejected_list',
            new_name='srejected_list',
        ),
    ]
