# Generated by Django 2.0.3 on 2018-10-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20181025_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accepted_list',
            name='accepted_name',
        ),
        migrations.AddField(
            model_name='accepted_list',
            name='accepted_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RemoveField(
            model_name='pending_list',
            name='pending_name',
        ),
        migrations.AddField(
            model_name='pending_list',
            name='pending_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RemoveField(
            model_name='rejected_list',
            name='rejected_name',
        ),
        migrations.AddField(
            model_name='rejected_list',
            name='rejected_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RemoveField(
            model_name='spending_list',
            name='spending_name',
        ),
        migrations.AddField(
            model_name='spending_list',
            name='spending_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RemoveField(
            model_name='srejected_list',
            name='srejected_name',
        ),
        migrations.AddField(
            model_name='srejected_list',
            name='srejected_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
