# Generated by Django 2.0.3 on 2018-10-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20181025_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='names',
            name='user',
        ),
        migrations.DeleteModel(
            name='Names',
        ),
    ]
